### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jbrooksuk** [shentao/vue-multiselect#1527]
```
/Users/james/Code/laravel/forge/node_modules/vue-multiselect/dist/vue-multiselect.esm.js:1
import { openBlock, createBlock, withKeys, withModifiers, renderSlot, createVNode, withDirectives, Fragment, renderList, toDisplayString, vShow, createCommentVNode, Transition, withCtx, createTextVNode } from 'vue';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.5484 (/Users/james/Code/laravel/forge/public/js/ssr.js:1:1540400)
    at o (/Users/james/Code/laravel/forge/public/js/ssr.js:1:1540654)
```

**Comment by jbrooksuk** [comment]
Has anyone managed to resolve this at all? I'm building with Laravel Mix and I've tried transpiling during compilation with no luck.

**Comment by raimund-schluessler** [comment]
I got the same error when running tests with Jest and this `transformIgnorePatterns` helped:
```json
"transformIgnorePatterns": [
	"/node_modules/(?!(.*vue-multiselect))"
],
```

**Comment by mattelen** [comment]
Hi @jbrooksuk. Thanks for opening up an issue around this. I'm unfamiliar with SSR, so are you able to create a reproducible repo so I can figure out how best we can fix this?

**Comment by davimug** [comment]
@jbrooksuk did you manage to find a fix?

**Comment by phlegx** [comment]
Hi! I have the same problem using 3.0.0-beta.2 and Vite 4.x with `import Multiselect from 'vue-multiselect'.

For me it works by adding `"type": "module",` to vue-multiselect package.json.

**Comment by gustawdaniel** [comment]
@paul-jolimoi in my case

```
'^vue-multiselect$': 'vue-multiselect/dist/vue-multiselect.common.js',
```

with `vue-multiselect` instead of `vue3-multiselect.`

**Comment by phlegx** [comment]
@Seeman13 thx! But what if you dont want to use esnext and work with legacy plugin?

**Comment by Seeman13** [comment]
> @Seeman13 thx! But what if you dont want to use esnext and work with legacy plugin?

Well then, if you work with a deprecated plugin, then use Vue 2 or even better Vue 1 - and work with everything outdated! If you use the new, and then need work with the new!

**Comment by jet4419** [comment]
> Hi! I have the same problem using 3.0.0-beta.2 and Vite 4.x with `import Multiselect from 'vue-multiselect'.
> 
> For me it works by adding `"type": "module",` to vue-multiselect package.json.
> 
> `Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

Thanks a lot, man! Managed to sort out that same issue on my end using this workaround.

**Comment by ms264556** [comment]
If you're getting this issue with a VitePress site, then the correct fix is here: [https://github.com/vuejs/vitepress/issues/4083](https://github.com/vuejs/vitepress/issues/4083#issuecomment-2254574563)

**Comment by Stalinko** [comment]
I have Vue3 with SSR and Vite.
Fixed by adding this into vite.config.js:

```js
export default defineConfig({
  ...
  ssr: {
    noExternal: ['vue-multiselect'],
  },
  ...
});
```
